name: 'Version Check Gradle'
description: 'Check if there is already a package published with the current version'
branding:
  icon: chevrons-up
inputs:
  access-token:
    required: true
    description: 'Personal access token with package read access'
  organization:
    required: false
    description: 'If the package belongs to an organization, the org name'
outputs:
  changed:
    description: 'True if the current package version has not been published'
runs:
  using: 'node16'
  main: 'dist/index.js'
